# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Inicio"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "HowTo"
  pageRef = "how"
  weight = 30

[[main]]
  name = "Apps"
  pageRef = "apps"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/proyectopy"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "twitter"
  url = "https://twitter.com/Raspyserver"
  weight = 110


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.



[[footer]]
  name = "|&nbsp;&nbsp;&nbsp;&nbsp;Aviso Legal"
  pageRef = "legal/aviso"
  weight = 10

[[footer]]
  name = "|&nbsp;&nbsp;&nbsp;&nbsp;Privacidad"
  pageRef = "legal/privacidad"
  weight = 20
 
[[footer]]
  name = "|&nbsp;&nbsp;&nbsp;&nbsp;Licencia MIT"
  pageRef = "legal/licencia"
  weight = 30  
  
